[build]
  command = "npm run install:all && npm run build"
  publish = "client/dist"
  base = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Opt out of Google's FLoC tracking
[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()" 